// Embeds the ExtendScript host files into AppleFX/js/host_src.js so the panel can
// load them with evalScript() directly, without depending on file paths.
// Run after editing anything in AppleFX/jsx/:  npm run build
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', 'AppleFX');
const read = (f) => fs.readFileSync(path.join(root, 'jsx', f), 'utf8');
const src = { AEFT: read('host_ae.jsx'), PPRO: read('host.jsx') };
for (const [k, v] of Object.entries(src)) {
  if (/[^\x00-\x7f]/.test(v)) throw new Error(k + ' host script must be ASCII-only');
}
const out = '/* Generated by tools/build-host.js from AppleFX/jsx/*.jsx. Do not edit. */\n' +
  '(function (root) {\n  root.AFX = root.AFX || {};\n  root.AFX.HOST_SRC = ' + JSON.stringify(src) + ';\n})(window);\n';
const file = path.join(root, 'js', 'host_src.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== out) {
    console.error('AppleFX/js/host_src.js is out of date. Run: npm run build');
    process.exit(1);
  }
  console.log('host_src.js is up to date');
} else {
  fs.writeFileSync(file, out);
  console.log('wrote', path.relative(process.cwd(), file), out.length, 'bytes');
}
